services:
  # PostgreSQL Database
  postgres:
    image: postgres:18-alpine
    container_name: payment-flow-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: payment_flow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-flow-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:8-alpine
    container_name: payment-flow-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - payment-flow-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

  # # Backend API (NestJS)
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: payment-flow-backend
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     NODE_ENV: production
  #     PORT: 3000
  #     DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/payment_flow?schema=public
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-dev-super-secret-jwt-access-key-2025-payment-flow}
  #     JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-dev-super-secret-jwt-refresh-key-2025-payment-flow}
  #     JWT_ACCESS_EXPIRATION: 15m
  #     JWT_REFRESH_EXPIRATION: 7d
  #     API_PREFIX: api/v1
  #     DEFAULT_CURRENCY: USD
  #     MINIMUM_WITHDRAWAL: 1.00
  #     MAXIMUM_DEPOSIT: 10000.00
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   networks:
  #     - payment-flow-network
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   command: sh -c "npx prisma migrate deploy && npm run start:prod"

  # pgAdmin (Database Management UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: payment-flow-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@payment-flow.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - payment-flow-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  payment-flow-network:
    driver: bridge